name: Testing

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        node: [ '16' ]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }}-${{matrix.os}} tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run lint
      - run: npm test
